//! Build script for `mantis`.
//!
//! Compiles the bundled plugin crates (`mantis-plugin-iconize`,
//! `mantis-plugin-markdown`) and embeds their binaries as `&[u8]` constants
//! into a file at `$OUT_DIR/plugin_binaries.rs`. This removes the search-path
//! dance from `install_one_binary` and ensures bundled plugins are always
//! available — even for non-source installs (release artifacts, Homebrew, etc.).
//!
//! The generated file is included by `src/plugin/install.rs` via
//! `include!(concat!(env!("OUT_DIR"), "/plugin_binaries.rs"))`.
//!
//! Rebuilds are gated on `build.rs` and the plugin source files.
//!
//! ## Lock-free plugin builds
//!
//! Plugin crates are compiled into a **dedicated target directory** beneath the
//! main `target/` (`target/mantis-plugin-build/`) so the inner `cargo build`
//! does not contend for the file lock that the outer cargo process holds on
//! the main target directory. Without this, the recursive cargo invocation
//! deadlocks.

use std::path::PathBuf;
use std::process::Command;

fn main() {
    let plugins = &["mantis-plugin-iconize", "mantis-plugin-markdown"];

    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let is_release = profile == "release";
    // Cargo sets TARGET to the triple being built for, which may differ from
    // the host triple during cross-compilation (e.g. building
    // x86_64-apple-darwin on an aarch64 macos-latest runner). Plugins must be
    // built for the same triple or the embedded binaries won't run.
    let target_triple = std::env::var("TARGET").expect("TARGET must be set by cargo");
    let is_windows_target = target_triple.contains("windows");

    let target_dir = resolve_target_dir();
    // Separate target dir for plugin builds so the inner cargo does not
    // contend for the file lock the outer cargo holds on the main target dir.
    let plugin_target = target_dir.join("mantis-plugin-build");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let out_path = PathBuf::from(&out_dir).join("plugin_binaries.rs");

    // Signal to cargo when to re-run build.rs
    println!("cargo:rerun-if-changed=build.rs");
    for pkg in plugins {
        let src_dir = format!("plugins/{pkg}/src");
        println!("cargo:rerun-if-changed=plugins/{pkg}/Cargo.toml");
        if let Ok(entries) = std::fs::read_dir(&src_dir) {
            for entry in entries.flatten() {
                if entry.path().extension().is_some_and(|e| e == "rs") {
                    println!("cargo:rerun-if-changed={}", entry.path().display());
                }
            }
        }
    }

    // Build each plugin crate into the dedicated plugin target directory,
    // for the same target triple as the outer build.
    for &pkg in plugins {
        let mut cmd = Command::new("cargo");
        cmd.args([
            "build",
            "--package",
            pkg,
            "--target",
            &target_triple,
            "--target-dir",
            plugin_target.to_str().unwrap(),
        ]);
        if is_release {
            cmd.arg("--release");
        }
        let status = cmd.status().unwrap_or_else(|e| {
            panic!("failed to execute cargo build for {pkg}: {e}");
        });
        assert!(
            status.success(),
            "cargo build for {pkg} failed (exit: {})",
            status,
        );
    }

    // Read binaries and generate source
    let mut output = String::from("// Generated by build.rs. Do not edit.\n\n");

    for &pkg in plugins {
        let binary_name = if is_windows_target {
            format!("{pkg}.exe")
        } else {
            pkg.to_string()
        };
        let binary_path = plugin_target
            .join(&target_triple)
            .join(&profile)
            .join(&binary_name);
        let data: Vec<u8> = std::fs::read(&binary_path).unwrap_or_else(|e| {
            panic!("failed to read {pkg} binary at {:?}: {e}", binary_path);
        });
        let const_name = pkg.replace('-', "_").to_uppercase();
        output.push_str(&format!(
            "pub(crate) const {}: &[u8] = &{:?};\n\n",
            const_name, data,
        ));
    }

    std::fs::write(&out_path, &output).unwrap_or_else(|e| {
        panic!("failed to write {:?}: {e}", out_path);
    });
}

/// Resolve the workspace-level `target/` directory.
///
/// This crate's `Cargo.toml` is itself the workspace root (it has both
/// `[package]` and `[workspace]`), so the target dir is `<manifest_dir>/target`
/// unless overridden by `CARGO_TARGET_DIR`.
fn resolve_target_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("CARGO_TARGET_DIR") {
        return PathBuf::from(dir);
    }
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by cargo");
    PathBuf::from(&manifest_dir).join("target")
}
