[changelog]
filter_commit_regex = "\\[skip ci\\]"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = "0.1.0"
no_increment_regex = "^(build|chore|ci|docs|refactor|style|test)(\\([^)]*\\))?:"
