background = "#eff1f5"
accent = "#1e66f5"
accent_alt = "#df8e1d"
dim = "#9ca0b0"
text = "#4c4f69"
dir = "#1e66f5"
file = "#4c4f69"
selection_bg = "#ccd0da"
selection_fg = "#df8e1d"
heading1 = "#04a5e5"
heading2 = "#df8e1d"
heading3 = "#40a02b"
code = "#df8e1d"
diff_add = "#40a02b"
diff_del = "#d20f39"
git_clean = "#40a02b"
git_dirty = "#df8e1d"
git_conflict = "#d20f39"
git_progress = "#fe640b"
breadcrumb_fg = "#1e66f5"
breadcrumb_bg = "#eff1f5"
active_line_bg = "#e0e4f0"
syntax = "base16-ocean.light"
