background = "reset"
accent = "cyan"
accent_alt = "yellow"
dim = "darkgray"
text = "white"
dir = "blue"
file = "reset"
selection_bg = "#505050"
selection_fg = "yellow"
heading1 = "lightcyan"
heading2 = "lightyellow"
heading3 = "lightgreen"
code = "lightyellow"
diff_add = "green"
diff_del = "red"
git_clean = "green"
git_dirty = "yellow"
git_conflict = "red"
git_progress = "#ff8700"
breadcrumb_fg = "cyan"
breadcrumb_bg = "reset"
syntax = "base16-ocean.dark"
