background = "#272822"
accent = "#66d9ef"
accent_alt = "#e6db74"
dim = "#75715e"
text = "#f8f8f2"
dir = "#66d9ef"
file = "#f8f8f2"
selection_bg = "#49483e"
selection_fg = "#e6db74"
heading1 = "#66d9ef"
heading2 = "#e6db74"
heading3 = "#a6e22e"
code = "#e6db74"
diff_add = "#a6e22e"
diff_del = "#f92672"
git_clean = "#a6e22e"
git_dirty = "#e6db74"
git_conflict = "#f92672"
git_progress = "#fd971f"
breadcrumb_fg = "#66d9ef"
breadcrumb_bg = "#272822"
syntax = "base16-eighties.dark"
