background = "#002b36"
accent = "#268bd2"
accent_alt = "#b58900"
dim = "#586e75"
text = "#93a1a1"
dir = "#268bd2"
file = "#839496"
selection_bg = "#073642"
selection_fg = "#b58900"
heading1 = "#2aa198"
heading2 = "#b58900"
heading3 = "#859900"
code = "#b58900"
diff_add = "#859900"
diff_del = "#dc322f"
git_clean = "#859900"
git_dirty = "#b58900"
syntax = "Solarized (dark)"
