background = "#fdf6e3"
accent = "#268bd2"
accent_alt = "#b58900"
dim = "#93a1a1"
text = "#657b83"
dir = "#268bd2"
file = "#586e75"
selection_bg = "#eee8d5"
selection_fg = "#b58900"
heading1 = "#2aa198"
heading2 = "#b58900"
heading3 = "#859900"
code = "#b58900"
diff_add = "#859900"
diff_del = "#dc322f"
git_clean = "#859900"
git_dirty = "#b58900"
git_conflict = "#dc322f"
git_progress = "#cb4b16"
syntax = "Solarized (light)"
