background = "#262335"
accent = "#36f9f6"
accent_alt = "#ff7edb"
dim = "#848bbd"
text = "#f0eff1"
dir = "#36f9f6"
file = "#f0eff1"
selection_bg = "#463465"
selection_fg = "#fede5d"
heading1 = "#36f9f6"
heading2 = "#fede5d"
heading3 = "#72f1b8"
code = "#fede5d"
diff_add = "#72f1b8"
diff_del = "#f92aad"
git_clean = "#72f1b8"
git_dirty = "#fede5d"
git_conflict = "#fe4450"
git_progress = "#ff8b39"
syntax = "base16-eighties.dark"
